name: Build and test

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Build
        run: |
          docker build . -t calibrator
      - 
        name: Test
        run: |
          docker run --rm -t calibrator /bin/bash -c 'cd build && ctest'
